/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ftc6210.main;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Stroke;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author Busch_902818
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MainWindow
     */
    
    private PointModel redPoints;
    private PointModel bluePoints;
    private BufferedImage fieldImage;
    private Point selectedPoint, draggedPoint;
    
    public MainWindow() throws IOException {
        initComponents();
        
        redPoints = new PointModel(false);
        bluePoints = new PointModel(true);
       
        fieldImage = ImageIO.read(getClass().getClassLoader().getResourceAsStream("res/field.png"));
        
        //  Update 30 times a second
        Timer timer = new Timer(1000/60, this);
        timer.start();
        
        speedSlider_jSlider.setMinimum(0);
        speedSlider_jSlider.setMaximum(100);
        speedSlider_jSlider.setMajorTickSpacing(1);
        
        setSelectedPoint(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabs_jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        currentPointName_jTextField = new javax.swing.JTextField();
        speedSlider_jSlider = new javax.swing.JSlider();
        speed_jLabel = new javax.swing.JLabel();
        customCode_jButton = new javax.swing.JButton();
        notes_jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes_jTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        points_jList = new javax.swing.JList();
        fieldView_jPanel = new FieldView(this);
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        redAlliance_jTextArea = new javax.swing.JTextArea();
        copyRed_jButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        blueAlliance_jTextArea = new javax.swing.JTextArea();
        copyBlue_jButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        currentPointName_jTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        currentPointName_jTextField.setText("Point");

        speed_jLabel.setText("Speed");

        customCode_jButton.setText("Custom Code");
        customCode_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customCode_jButtonActionPerformed(evt);
            }
        });

        notes_jLabel.setText("Notes");

        notes_jTextArea.setColumns(20);
        notes_jTextArea.setRows(5);
        jScrollPane1.setViewportView(notes_jTextArea);

        points_jList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(points_jList);

        fieldView_jPanel.setPreferredSize(new java.awt.Dimension(360, 360));
        fieldView_jPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldView_jPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldView_jPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fieldView_jPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout fieldView_jPanelLayout = new javax.swing.GroupLayout(fieldView_jPanel);
        fieldView_jPanel.setLayout(fieldView_jPanelLayout);
        fieldView_jPanelLayout.setHorizontalGroup(
            fieldView_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        fieldView_jPanelLayout.setVerticalGroup(
            fieldView_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldView_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customCode_jButton)
                    .addComponent(notes_jLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(speed_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speedSlider_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(currentPointName_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(currentPointName_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(speedSlider_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speed_jLabel))
                        .addGap(18, 18, 18)
                        .addComponent(customCode_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notes_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(fieldView_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainTabs_jTabbedPane.addTab("Draw", jPanel1);

        redAlliance_jTextArea.setColumns(20);
        redAlliance_jTextArea.setRows(5);
        jScrollPane3.setViewportView(redAlliance_jTextArea);

        copyRed_jButton.setText("Copy Code");
        copyRed_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyRed_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(copyRed_jButton)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyRed_jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabs_jTabbedPane.addTab("Red Alliance", jPanel3);

        blueAlliance_jTextArea.setColumns(20);
        blueAlliance_jTextArea.setRows(5);
        jScrollPane4.setViewportView(blueAlliance_jTextArea);

        copyBlue_jButton.setText("Copy Code");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(copyBlue_jButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyBlue_jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabs_jTabbedPane.addTab("Blue Alliance", jPanel4);

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabs_jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTabs_jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customCode_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customCode_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customCode_jButtonActionPerformed

    private void copyRed_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyRed_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyRed_jButtonActionPerformed

    private void fieldView_jPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldView_jPanelMouseReleased
        java.awt.Point mouse = fieldView_jPanel.getMousePosition();
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
            draggedPoint = null;
        
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON3)
            setSelectedPoint(redPoints.addPoint(evt.getX(), evt.getY(), "Point" + (redPoints.getPoints().size() + 1)));
            
        
    }//GEN-LAST:event_fieldView_jPanelMouseReleased

    private void fieldView_jPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldView_jPanelMouseClicked

    }//GEN-LAST:event_fieldView_jPanelMouseClicked

    private void fieldView_jPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldView_jPanelMousePressed
        java.awt.Point mouse = fieldView_jPanel.getMousePosition();
        
        if(mouse == null)return;
        
        
        Point toSelect = null;
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1) // LEFT CLICK TO DRAG
            for(Point p : redPoints) {
                Rectangle hitbox = new Rectangle(p.getX()-5, p.getY() -5, 10, 10);
                if(hitbox.contains(mouse)) {
                    toSelect = p;
                    break;
                }
            }
        
        if(draggedPoint == null)
            draggedPoint = toSelect;
        if(toSelect != null)
            setSelectedPoint(toSelect);
        
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON2) {
            
        }
        
    }//GEN-LAST:event_fieldView_jPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWindow().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea blueAlliance_jTextArea;
    private javax.swing.JButton copyBlue_jButton;
    private javax.swing.JButton copyRed_jButton;
    private javax.swing.JTextField currentPointName_jTextField;
    private javax.swing.JButton customCode_jButton;
    private javax.swing.JPanel fieldView_jPanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane mainTabs_jTabbedPane;
    private javax.swing.JLabel notes_jLabel;
    private javax.swing.JTextArea notes_jTextArea;
    private javax.swing.JList points_jList;
    private javax.swing.JTextArea redAlliance_jTextArea;
    private javax.swing.JSlider speedSlider_jSlider;
    private javax.swing.JLabel speed_jLabel;
    // End of variables declaration//GEN-END:variables

    
    // Handle all of the animations from the image view
    @Override
    public void actionPerformed(ActionEvent e) {
        
        
        Graphics g = fieldView_jPanel.getGraphics();
        
        if(mainTabs_jTabbedPane.getSelectedIndex() != 0){
            g.dispose();
            return;
        }
        
        pointLogic();
        fieldView_jPanel.paintComponents(g);
        
    }
    
    public void pointLogic() {
        
        java.awt.Point mouse = fieldView_jPanel.getMousePosition();
        
        if(mouse != null) {
            if(draggedPoint != null) {
                draggedPoint.setX(mouse.x);
                draggedPoint.setY(mouse.y);
            }
        }
                 
    }
    
    public void setSelectedPoint(Point p) {
        selectedPoint = p;
        if(selectedPoint == null){
            currentPointName_jTextField.setEnabled(false);
            notes_jTextArea.setEnabled(false);
            speedSlider_jSlider.setEnabled(false);
            return;
        }
        currentPointName_jTextField.setEnabled(true);
        notes_jTextArea.setEnabled(true);
        speedSlider_jSlider.setEnabled(true);
        
        currentPointName_jTextField.setText(p.getName());
        notes_jTextArea.setText(p.getNotes());
        speedSlider_jSlider.setValue(p.getSpeed());
        
    }

    public PointModel getRedPoints() {
        return redPoints;
    }

    public PointModel getBluePoints() {
        return bluePoints;
    }

    public BufferedImage getFieldImage() {
        return fieldImage;
    }

    public Point getSelectedPoint() {
        return selectedPoint;
    }
    
    
    
}
